.\" generated with Ronn-NG/v0.10.1
.\" http://github.com/apjanke/ronn-ng/tree/0.10.1
.TH "TOR\-CONTROL\-PANEL" "8" "January 2020" "tor-control-panel" "tor-control-panel Manual"
.SH "NAME"
\fBtor\-control\-panel\fR \- Tor Controller
.SH "SYNOPSIS"
tor\-control\-panel
.SH "DESCRIPTION"
tor\-control\-panel is a Tor controller\.
.P
tor\-control\-panel is produced independently from the Tor anonymity software and carries no guarantee from The Tor Project about quality, suitability or anything else\.
.SH "WWW"
https://www\.whonix\.org
.SH "AUTHOR"
This man page has been written by troubadour (trobador@riseup\.net)\.
