/usr/share/genmkfile/make-helper.bsh deb-icup
./
./make
./changelog.upstream
./etc/
./etc/sudoers.d/
./etc/sudoers.d/tor-control-panel
./etc/sudoers.d/restart-tor-gui
./CONTRIBUTING.md
./README.md
./man/
./man/restart-tor-gui.8.ronn
./man/tor-control-panel.8.ronn
./debian/
./debian/changelog
./debian/watch
./debian/control
./debian/copyright
./debian/compat
./debian/source/
./debian/source/lintian-overrides
./debian/source/format
./debian/rules
./debian/gain-root-command
./GPLv3
./COPYING
./usr/
./usr/share/
./usr/share/tor-control-panel/
./usr/share/tor-control-panel/refresh.png
./usr/share/tor-control-panel/onion.png
./usr/share/tor-control-panel/onion64.png
./usr/share/tor-control-panel/help.png
./usr/share/tor-control-panel/restart.png
./usr/share/tor-control-panel/prev.png
./usr/share/tor-control-panel/bridges_default
./usr/share/tor-control-panel/back_icon.png
./usr/share/tor-control-panel/Exit.png
./usr/share/tor-control-panel/tools.png
./usr/share/tor-control-panel/silhouette2.png
./usr/share/tor-control-panel/silhouette1.png
./usr/share/tor-control-panel/stop.png
./usr/share/tor-control-panel/accept_icon.png
./usr/share/applications/
./usr/share/applications/restart-tor-gui.desktop
./usr/share/applications/tor-control-panel.desktop
./usr/lib/
./usr/lib/python3/
./usr/lib/python3/dist-packages/
./usr/lib/python3/dist-packages/tor_control_panel/
./usr/lib/python3/dist-packages/tor_control_panel/info.py
./usr/lib/python3/dist-packages/tor_control_panel/repair_torrc.py
./usr/lib/python3/dist-packages/tor_control_panel/tor_control_panel.py
./usr/lib/python3/dist-packages/tor_control_panel/tor_bootstrap.py
./usr/lib/python3/dist-packages/tor_control_panel/tor_status.py
./usr/lib/python3/dist-packages/tor_control_panel/restart_tor_gui.py
./usr/lib/python3/dist-packages/tor_control_panel/__init__.py
./usr/lib/python3/dist-packages/tor_control_panel/torrc_gen.py
./usr/lib/tor-control-panel/
./usr/lib/tor-control-panel/tor-control-panel
./usr/lib/restart-tor-gui/
./usr/lib/restart-tor-gui/restart-tor-gui
./usr/bin/
./usr/bin/tor-control-panel
./usr/bin/restart-tor-gui
./Makefile
/usr/share/genmkfile/makefile-full:68: recipe for target 'deb-icup' failed
/usr/share/genmkfile/make-helper.bsh deb-icup
./
./make
./changelog.upstream
./etc/
./etc/sudoers.d/
./etc/sudoers.d/tor-control-panel
./etc/sudoers.d/restart-tor-gui
./CONTRIBUTING.md
./README.md
./man/
./man/restart-tor-gui.8.ronn
./man/tor-control-panel.8.ronn
./debian/
./debian/changelog
./debian/watch
./debian/control
./debian/copyright
./debian/compat
./debian/source/
./debian/source/lintian-overrides
./debian/source/format
./debian/rules
./debian/gain-root-command
./GPLv3
./COPYING
./usr/
./usr/share/
./usr/share/tor-control-panel/
./usr/share/tor-control-panel/refresh.png
./usr/share/tor-control-panel/onion.png
./usr/share/tor-control-panel/onion64.png
./usr/share/tor-control-panel/help.png
./usr/share/tor-control-panel/restart.png
./usr/share/tor-control-panel/prev.png
./usr/share/tor-control-panel/bridges_default
./usr/share/tor-control-panel/back_icon.png
./usr/share/tor-control-panel/Exit.png
./usr/share/tor-control-panel/tools.png
./usr/share/tor-control-panel/silhouette2.png
./usr/share/tor-control-panel/silhouette1.png
./usr/share/tor-control-panel/stop.png
./usr/share/tor-control-panel/accept_icon.png
./usr/share/applications/
./usr/share/applications/restart-tor-gui.desktop
./usr/share/applications/tor-control-panel.desktop
./usr/lib/
./usr/lib/python3/
./usr/lib/python3/dist-packages/
./usr/lib/python3/dist-packages/tor_control_panel/
./usr/lib/python3/dist-packages/tor_control_panel/info.py
./usr/lib/python3/dist-packages/tor_control_panel/repair_torrc.py
./usr/lib/python3/dist-packages/tor_control_panel/tor_control_panel.py
./usr/lib/python3/dist-packages/tor_control_panel/tor_bootstrap.py
./usr/lib/python3/dist-packages/tor_control_panel/tor_status.py
./usr/lib/python3/dist-packages/tor_control_panel/restart_tor_gui.py
./usr/lib/python3/dist-packages/tor_control_panel/__init__.py
./usr/lib/python3/dist-packages/tor_control_panel/torrc_gen.py
./usr/lib/tor-control-panel/
./usr/lib/tor-control-panel/tor-control-panel
./usr/lib/restart-tor-gui/
./usr/lib/restart-tor-gui/restart-tor-gui
./usr/bin/
./usr/bin/tor-control-panel
./usr/bin/restart-tor-gui
./Makefile
/usr/share/genmkfile/makefile-full:68: recipe for target 'deb-icup' failed
