#!/usr/bin/python3 -u

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

from subprocess import call
import sys, os
import time
import shutil

restart_tor_gui = shutil.which("restart-tor-gui")
if restart_tor_gui == None:
    print('ERROR: restart-tor-gui not found! Exiting.')
    sys.exit(1)

command = 'xhost +local:root'
call(command, shell = True)

command = 'kdesudo {}'.format(restart_tor_gui)
call(command, shell=True)
