#!/usr/bin/python3 -u

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

from subprocess import call
import sys, os
import time

command = 'xhost +local:root'
call(command, shell = True)

command = 'kdesudo /usr/bin/restart-tor-gui'
call(command, shell=True)
