#!/usr/bin/python3 -u

## Copyright (C) 2012 - 2018 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

from subprocess import call
import sys, os
import time
import shutil

tor_control_panel = shutil.which("tor-control-panel")
if tor_control_panel == None:
    print('ERROR: tor-control-panel not found! Exiting.')
    sys.exit(1)

command = 'xhost +local:root'
call(command, shell = True)

command = 'kdesudo {}'.format(tor_control_panel)
call(command, shell=True)
